### PR TITLE
Firestore: encoding & decoding strategies

### PR DESCRIPTION
**Pull request by mshershnev**
For now you can use encoding & decoding strategies for Firestore.

This request fix issue #44

### CODE REVIEW

**Comment by mshershnev** [comment]
`{
        let decoder = FirestoreDecoder()

        decoder.dateDecodingStrategy = .custom { decoder -> Date in
            let container = try decoder.singleValueContainer()
            let timestamp = try container.decode(Timestamp.self)

            return timestamp.dateValue()
        }
    }`

**Comment by mshershnev** [comment]
```
let decoder = FirestoreDecoder()

        decoder.dateDecodingStrategy = .custom { decoder -> Date in
            let container = try decoder.singleValueContainer()
            let timestamp = try container.decode(Timestamp.self)

            return timestamp.dateValue()
        }
```

**Comment by mshershnev** [comment]
```
        let decoder = FirestoreDecoder()

        decoder.dateDecodingStrategy = .custom { decoder -> Date in
            let container = try decoder.singleValueContainer()
            let timestamp = try container.decode(Timestamp.self)

            return timestamp.dateValue()
        }
```

**Comment by Moriquendi** [comment]
👍

**Comment by otri** [comment]
@mshershnev love it!
But, I get a warning:
`Instance method 'decode' requires that 'Timestamp' conform to 'Decodable'`

Wondering how you managed to get Timestamp to be decodable?

**Comment by otri** [comment]
Unfortunately, after a lot of effort to make **CodableFirebase** better, I realized that Google's finished the complete solution in:
`
pod 'FirebaseFirestoreSwift'
`

Use `Firestore.Decoder()` directly.  This will decode your struct Date() types correctly.

**Comment by mshershnev** [comment]
@otri try to add 4 extensions:

```
extension GeoPoint: GeoPointType {}
extension Timestamp: TimestampType {}
extension FieldValue: FieldValueType {}
extension DocumentReference: DocumentReferenceType {}
```

**Comment by yvetterowe** [comment]
> Unfortunately, after a lot of effort to make **CodableFirebase** better, I realized that Google's finished the complete solution in:
> `pod 'FirebaseFirestoreSwift'`
> 
> Use `Firestore.Decoder()` directly. This will decode your struct Date() types correctly.

Thanks for the reference! Took me a decade to realize Google already supports this

**Pull request closed without merging**
